### ISSUE TITLE
Recommend MIT/Apache 2.0 duo license

### ISSUE THREAD

**Issue by kinggoesgaming** [onehr/crust#3]
Most the Rust community follows with the `Apache 2.0/ MIT` license duo.

Plus I want to contribute but I am seriously opposed to any GPL projects.

**Comment by onehr** [comment]
Ok, then I will try to follow the community, cause I don't know too much about Rust now.

**Comment by onehr** [comment]
I have already change the license, if you want to.contribute, it's very welcome @kinggoesgaming .
